export const checkedAt = '2026-09-19';
export const majors = {
  cybersecurity: { name: 'Cybersecurity', topics: ['cybersecurity','security','privacy','ethics','networks','risk'] },
  business: { name: 'Business', topics: ['business','career','leadership','marketing','finance','networking'] },
  'musical-theatre': { name: 'Musical Theatre', topics: ['arts','theatre','music','performance','creative','design','entertainment'] }
};
// Editorial snapshots of public sources. No fictional dates, availability, or event locations.
const seeds = [
 ['cyber-program','Cybersecurity: technical and policy tracks','Rider University','https://www.rider.edu/programs/cybersecurity','Academics','resource','Rider offers technical and policy tracks in its cybersecurity degree. The program combines security fundamentals with practical learning and internship experience.',['cybersecurity'],['cybersecurity','security','networks','ethics'],null],
 ['cs-program','Cybersecurity and computing program context','Rider University','https://www.rider.edu/programs/computer-science','Academics','resource','This computing program page provides adjacent context for students interested in cybersecurity, software and artificial intelligence. Verify current program requirements in the catalog.',['cybersecurity'],['programming','algorithms','software','ai','cybersecurity'],null],
 ['bda-program','Business Analytics: using data to solve business problems','Rider University','https://www.rider.edu/programs/business-analytics','Academics','resource','Rider’s business analytics program combines technology and business study to develop analytical skills and communicate actionable insights. It is included as business-related context, not as a selectable major in this demo.',['business'],['analytics','business','data','ai'],null],
 ['bda-catalog','Business Analytics: curriculum and experiential learning','Rider University','https://catalog.rider.edu/undergraduate/colleges-schools/business-administration/business-analytics/','Academics','resource','The catalog lists visual analytics, Python, database systems, Excel and R, data mining, and a practicum among business-related coursework. Check the catalog for prerequisites and your applicable degree requirements.',['business'],['analytics','databases','programming','visualization'],null],
 ['cyber-minor','Cybersecurity minor','Rider University','https://www.rider.edu/academics/colleges-schools/college-arts-sciences/science-technology-math/undergraduate/cybersecurity-minor','Academics','resource','The cybersecurity minor covers identifying security risks and using technical solutions, policies and procedures to manage threats. Consult the catalog and an adviser for eligibility.',['cybersecurity'],['security','risk','privacy','cybersecurity'],null],
 ['analytics-experience','Business analytics: internship, co-op and practicum courses','Rider University','https://catalog.rider.edu/undergraduate/course-descriptions/bda/','Career & Internships','resource','The catalog describes a practicum with real-world data, supervised internship and co-op courses. These are academic options, not currently advertised job openings; prerequisites and approval requirements apply.',['business'],['analytics','business','data','career'],null],
 ['enterprise-security','Information Technology Management: enterprise security and databases','Rider University','https://catalog.rider.edu/undergraduate/colleges-schools/business-administration/majors-minors-certificates/information-systems/','Academics','resource','This program’s catalog includes enterprise security, database systems, cloud infrastructure, and risk management electives. Related coursework may interest students exploring security, data systems or business technology.',['business'],['security','risk','databases','software','business'],null],
 ['analytics-lab','Business analytics lab opens in Sweigart Hall','Rider University','https://www.rider.edu/about/news/2019/02/01/new-business-data-analytics-lab-opens-sweigart-hall','Technology','news','This historical report describes an analytics lab with tools including Tableau, SAS, SAP and FactSet, serving several business disciplines. It is context, not confirmation of today’s software or lab access.',['business'],['analytics','data','business','visualization'],'2018-12-11'],
 ['ai-higher-ed','The rise of Artificial Intelligence in higher education','Rider News','https://theridernews.com/the-rise-of-artificial-intelligence-in-higher-education/','Technology','news','An April 2026 report discusses differing faculty approaches to AI and a cybersecurity student’s use of AI for resumes and brainstorming. This is reporting, not an official university AI policy.',['cybersecurity'],['ai','ethics','career','software'],'2026-04-22'],
 ['ai-ethics','Ethical struggles of artificial intelligence','Rider News','https://theridernews.com/ethical-struggles-of-artificial-intelligence/','Technology','news','A March 2024 opinion article discusses AI-generated creative work, impacts on creators, and ethical questions. Useful background for responsible technology discussions, not a current policy announcement.',[],['ai','ethics','software','business'],'2024-03-06'],
 ['rider-academics','Rider academics and experiential learning','Rider University','https://www.rider.edu/academics','Academics','resource','Rider describes internships, research, performances, capstone projects, study abroad and career preparation as part of its academic experience. This broad record is relevant across the three selected majors.',['cybersecurity','business','musical-theatre'],['career','internship','research','performance','leadership'],null],
 ['business-programs','Undergraduate business programs and Business in Action','Rider University','https://www.rider.edu/academics/colleges-schools/norm-brodsky-college-business/undergraduate','Academics','resource','Rider’s Norm Brodsky College of Business highlights hands-on learning, Business in Action, a student-run Saxbys café, internships, co-ops and a Business Living Learning Community.',['business'],['business','career','leadership','internship','entrepreneurship','networking'],null],
 ['musical-theatre-program','Musical Theatre B.F.A.: acting, performance and voice','Rider University','https://www.rider.edu/programs/musical-theatre','Academics','resource','Rider’s Musical Theatre B.F.A. integrates acting, music, dance and theatre. The program highlights performance training, faculty with professional experience, New York City connections and careers such as performer, choreographer, producer and production assistant.',['musical-theatre'],['arts','theatre','music','performance','creative','career','entertainment'],null],
 ['cyber-catalog','Cybersecurity B.S. in the 2026–2027 academic catalog','Rider University Academic Catalog','https://catalog.rider.edu/undergraduate/colleges-schools/arts-sciences/majors-minors-certificates/cybersecurity-bs/','Academics','resource','Rider’s current catalog describes Cybersecurity as a program aligned with national guidelines and adaptable to industry and research needs. Check the catalog for the official requirements and current course plan.',['cybersecurity'],['cybersecurity','security','networks','risk','research','technology'],null],
 ['program-finder','Rider Academic Program Finder','Rider University','https://www.rider.edu/academics/program-finder','Academics','resource','Rider’s program finder lists majors, minors and programs across arts, business, sciences and other areas. Use it to compare official program pages beyond this focused demo.',['cybersecurity','business','musical-theatre'],['academics','programs','arts','business','technology'],null],
 ['course-catalog','Rider course catalog and section search','Rider University','https://www.rider.edu/academics/course-catalog','Academics','resource','Rider’s course catalog provides program requirements and descriptions, while the section search tool can show course days, times, instructors and locations by semester.',['cybersecurity','business','musical-theatre'],['courses','academics','schedule','technology','arts','business'],null],
 ['career-fair-2026-09-24','General Internship and Career Fair 2026','Rider University','https://www.rider.edu/about/events/general-internship-and-career-fair','Career & Internships','event','Open to all Rider students and useful across majors, this career fair connects students with community business partners for internship and career opportunities. A free professional headshot is also offered.',['cybersecurity','business','musical-theatre'],['career','internship','jobs','networking','business','technology','arts'],null],
 ['dais-club','Data Analytics & Information Systems (DAIS) Club','Bronc Nation','https://broncnation.rider.edu/organization/dais','Student Organizations','organization','DAIS equips students for a data-driven world through professional networking, DataFest, AIS conferences and Tableau workshops. Its Bronc Nation page currently lists no upcoming public events.',['business'],['business','analytics','data','databases','networking'],null]
];
const clubRecords = [
 ['club-ama-2026-09-24','Arts Management Association General Meeting','Arts Management Association','https://broncnation.rider.edu/event/12781982','2026-09-24T18:15:00-04:00','Fine Arts Classroom 119',['musical-theatre','business'],['arts','creative','entertainment','networking'],'https://www.instagram.com/artsmgmtrider?utm_source=ig_web_button_share_sheet&igsh=ZDNlZC0wMzIxNw=='],
 ['club-hillel-2026-09-21','Hillel Kickoff Event','Hillel','https://broncnation.rider.edu/organization/hilllel','2026-09-21T18:30:00-04:00','Lynch Adler Hall Classroom 129',['business','musical-theatre'],['social','community','networking'],'https://www.instagram.com/hillelrider/'],
 ['club-poets-2026-09-21','The Rider Poets General Meeting','The Rider Poets','https://broncnation.rider.edu/event/12593788','2026-09-21T18:30:00-04:00','Lynch Adler Hall Classroom 126',['musical-theatre'],['arts','creative','writing'],'https://www.instagram.com/theriderpoets/?hl=en'],
 ['club-green-2026-09-22','Green Team Interest Meeting','Rider University Green Team','https://broncnation.rider.edu/event/12764404','2026-09-22T18:00:00-04:00','Schimek Student Recreation Center Shapiro Board Room',['business'],['community','leadership'],'https://www.instagram.com/rideruniversitygreenteam/'],
 ['club-crochet-2026-09-23','Rider Crochet Club Meeting','Rider University Crochet Club','https://broncnation.rider.edu/event/12765623','2026-09-23T18:30:00-04:00','SWG 110',['musical-theatre'],['arts','creative','social'],'https://www.instagram.com/ridercrochetclub/'],
 ['club-naacp-2026-09-23','Community and Culture Night','Rider University NAACP','https://broncnation.rider.edu/event/12772507','2026-09-23T18:30:00-04:00','Science 104',['business','musical-theatre'],['community','leadership','social'],'https://www.instagram.com/naacp_rider?igsh=eW43a29naHcwdDJl'],
 ['club-graphic-design-2026-10-22','Creepy Canvases: Halloween Event','Graphic Design Club','https://broncnation.rider.edu/event/12710686','2026-10-22T18:30:00-04:00','Fine Arts 205',['musical-theatre'],['arts','creative','design'],'https://www.instagram.com/ridergraphicdesign/'],
 ['club-venture-2026-09-29','Venture Magazine General Meeting','Venture Magazine','https://broncnation.rider.edu/event/12641410','2026-09-29T11:30:00-04:00','Fine Arts Classroom 321',['musical-theatre'],['arts','creative','writing'],'https://www.instagram.com/venture_litmagazine/'],
 ['club-radio-2026-10-23','Scream Screen','WRRC 107.7FM The Bronc Radio','https://broncnation.rider.edu/event/12680160','2026-10-23T18:00:00-04:00','BLC Visitors Parking Lot',['musical-theatre','business'],['arts','music','media','entertainment'],'https://www.instagram.com/1077thebronc/'],
 ['club-wrestling-2026-09-23','Women’s Wrestling Club Interest Meeting','Women’s Wrestling Club','https://broncnation.rider.edu/event/12766482','2026-09-23T17:30:00-04:00','Lynch Adler Hall Classroom 127',['business'],['community','leadership','social'],'https://www.instagram.com/riderwomenswrestling?stkn=MWVlazZ1cmhsaGVuZA%3D%3D&utm_source=qr']
].map(([id,title,org,sourceUrl,eventDate,location,directMajors,tags,socialUrl]) => ({id,title,source:'Bronc Nation',sourceUrl,category:'Club Event',type:'event',summary:`Public event listed by ${org}. Verify the event page before attending because club schedules can change.`,directMajors,tags,publishedAt:null,checkedAt:'2026-09-20',audience:['Students'],importance:'medium',eventDate,deadline:null,location,verification:'Bronc Nation public event listing',contentStatus:'Dated event snapshot',ingestion:'Public directory audit',socialLinks:[{platform:socialUrl.includes('instagram')?'Instagram':'Social',url:socialUrl}]}));
const backgroundOnly=new Set(['program-finder','course-catalog','rider-academics','cyber-program']);
export const records = [...seeds.map(([id,title,source,sourceUrl,category,type,summary,directMajors,tags,publishedAt]) => ({id,title,source,sourceUrl,category,type,summary,directMajors,tags,publishedAt,checkedAt,audience:['Students'],importance:type==='event'?'high':'low',eventDate:id==='career-fair-2026-09-24'?'2026-09-24T11:00:00-04:00':null,deadline:null,location:id==='career-fair-2026-09-24'?'Cavalla Room, Bart Luedeke Center':'',verification:'Public source reviewed',contentStatus:publishedAt?'Dated article':id==='career-fair-2026-09-24'?'Dated Rider event':'Reference record',feedVisible:!backgroundOnly.has(id),ingestion:'Editorial snapshot'})), ...clubRecords];
export function relevance(record, major) {
 const profile = majors[major]; if(!profile) return {score:0,reasons:[]};
 const direct=record.directMajors.includes(major), shared=record.tags.filter(t=>profile.topics.includes(t));
 const reasons=[]; if(direct) reasons.push('Direct subject mapping to '+profile.name+' (+3).');
 if(shared.length) reasons.push('Related topics: '+shared.join(', ')+' (+'+Math.min(shared.length,3)+').');
 if(record.id==='dais-club' && major==='cybersecurity') reasons.push('Possible adjacent interest in data systems, but this listing has no explicit security focus.');
 return {score:(direct?3:0)+Math.min(shared.length,3),reasons};
}
const stop=new Set('what which where when who how can could should would does do is are a an the at in of to for me my i about know anything related please rider university tell show'.split(' '));
export function searchRecords({major='cybersecurity',q='',source='',type='',category='',relevant=false}={}) {
 if(!majors[major]) throw new Error('Choose cybersecurity, business or musical-theatre.');
 const terms=q.toLowerCase().match(/[a-z0-9]+/g)?.filter(t=>!stop.has(t))||[];
 const normalized=terms.map(t=>({clubs:'club',courses:'course',internships:'internship',opportunities:'career',cyber:'cybersecurity',coding:'programming',jobs:'career'}[t]||t));
 return records.map(r=>({...r,relevance:relevance(r,major)})).map(r=>{
  const hay=(r.title+' '+r.summary+' '+r.category+' '+r.type+' '+r.tags.join(' ')).toLowerCase();
  return {...r,queryMatches:normalized.filter(t=>hay.includes(t)).length};
 }).filter(r=>(!source||r.source===source)&&(!type||r.type===type)&&(!category||r.category.toLowerCase().includes(category.toLowerCase()))&&(!relevant||r.relevance.score>0)&&(!normalized.length||r.queryMatches>0))
 .sort((a,b)=>a.eventDate&&b.eventDate?new Date(a.eventDate)-new Date(b.eventDate):a.eventDate?-1:b.eventDate?1:b.queryMatches-a.queryMatches||b.relevance.score-a.relevance.score||a.title.localeCompare(b.title));
}
export function retrieve(question,major) {
 const clean=String(question||'').trim();
 if(!clean||clean.length>500) throw new Error('Enter a question of 1–500 characters.');
 const temporal=/\b(today|tomorrow|this week|next week|upcoming|deadline|meeting time)\b/i.test(clean);
 const hits=temporal?searchRecords({major,relevant:true}).filter(r=>r.type==='event').slice(0,6):searchRecords({major,q:clean,relevant:true}).slice(0,4);
 return {mode:'Extractive retrieval; no language model connected',major,question:clean,answer:temporal?(hits.length?'These dated club events are currently stored in the knowledge base. Check the source link before attending because schedules can change.':'No dated club events are currently stored for this major.'):(hits.length?'These source records match your question and selected major. The summaries below come from the stored knowledge base.':'No matching source record was found. Try a topic such as AI, security, DAIS, databases or internships.'),citations:hits,checkedAt};
}
